In [21]:
import numpy as np
import pandas as pd

In [22]:
a = np.array([1, 2, 3])
a

array([1, 2, 3])

In [23]:
a.shape

(3,)

In [24]:
b = np.array([[1], [2], [3]])
b

array([[1],
       [2],
       [3]])

In [25]:
b.shape

(3, 1)

In [26]:
c = np.array([[1, 2, 3], [2, 2, 2], [3, 5, 6]])
c, c.shape

(array([[1, 2, 3],
        [2, 2, 2],
        [3, 5, 6]]),
 (3, 3))

In [27]:
np.ones((5, 2))

array([[1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.]])

In [28]:
np.ones((5, 2))*99

array([[99., 99.],
       [99., 99.],
       [99., 99.],
       [99., 99.],
       [99., 99.]])

In [29]:
np.full((3, 2, 3), 88)

array([[[88, 88, 88],
        [88, 88, 88]],

       [[88, 88, 88],
        [88, 88, 88]],

       [[88, 88, 88],
        [88, 88, 88]]])

In [30]:
c * 7

array([[ 7, 14, 21],
       [14, 14, 14],
       [21, 35, 42]])

In [31]:
np.log(c)

array([[0.        , 0.69314718, 1.09861229],
       [0.69314718, 0.69314718, 0.69314718],
       [1.09861229, 1.60943791, 1.79175947]])

In [32]:
c * c

array([[ 1,  4,  9],
       [ 4,  4,  4],
       [ 9, 25, 36]])

In [33]:
c

array([[1, 2, 3],
       [2, 2, 2],
       [3, 5, 6]])

In [34]:
c @ c

array([[14, 21, 25],
       [12, 18, 22],
       [31, 46, 55]])

In [35]:
np.dot(c, c)

array([[14, 21, 25],
       [12, 18, 22],
       [31, 46, 55]])

In [36]:
a

array([1, 2, 3])

In [37]:
np.dot(a, a)

np.int64(14)

In [38]:
d = np.array([[1, 2, 7], [3, 4, 8]])
d, d.shape

(array([[1, 2, 7],
        [3, 4, 8]]),
 (2, 3))

In [39]:
d.T, d.T.shape

(array([[1, 3],
        [2, 4],
        [7, 8]]),
 (3, 2))

In [40]:
np.dot(d, d)

ValueError: shapes (2,3) and (2,3) not aligned: 3 (dim 1) != 2 (dim 0)

In [41]:
np.dot(d, d.T)

array([[54, 67],
       [67, 89]])

In [42]:
x = np.array([[1, 2, 3]])
y = np.array([[7], [8], [9]])
x.shape, y.shape

((1, 3), (3, 1))

In [43]:
x, y

(array([[1, 2, 3]]),
 array([[7],
        [8],
        [9]]))

In [44]:
np.dot(y, x)

array([[ 7, 14, 21],
       [ 8, 16, 24],
       [ 9, 18, 27]])

In [45]:
np.dot(x, y)

array([[50]])

In [46]:
x.squeeze()
x, x.shape

(array([[1, 2, 3]]), (1, 3))

In [47]:
np.expand_dims(x, axis=-1).shape

(1, 3, 1)

In [48]:
c

array([[1, 2, 3],
       [2, 2, 2],
       [3, 5, 6]])

In [49]:
c.sum()

np.int64(26)

In [50]:
c.std()

np.float64(1.5234788000891208)

In [51]:
c.std()**2, c.var()

(np.float64(2.3209876543209873), np.float64(2.3209876543209877))

In [52]:
c.min(), c.max()

(np.int64(1), np.int64(6))

In [53]:
c.mean().item()

2.888888888888889

In [122]:
a, a.shape, b, b.shape

(array([1, 2, 3]),
 (3,),
 array([[1],
        [2],
        [3]]),
 (3, 1))

In [55]:
np.stack([np.expand_dims(a, axis=0), b.T]).shape

(2, 1, 3)

In [121]:
t = np.stack([np.expand_dims(a, axis=0), b.T])
t, t.shape

(array([[[1, 2, 3]],
 
        [[1, 2, 3]]]),
 (2, 1, 3))

In [56]:
np.concat([np.expand_dims(a, axis=0), b.T]).shape

(2, 3)

In [124]:
t = np.concat([np.expand_dims(a, axis=0), b.T])
t, t.shape

(array([[1, 2, 3],
        [1, 2, 3]]),
 (2, 3))

In [57]:
d.reshape(2, -1).shape

(2, 3)

In [58]:
a

array([1, 2, 3])

In [59]:
a[2]

np.int64(3)

In [60]:
a[1]

np.int64(2)

In [61]:
a[0]

np.int64(1)

In [62]:
a[0:2]

array([1, 2])

In [63]:
a[-1]

np.int64(3)

In [64]:
a[-2]

np.int64(2)

In [65]:
a[-3]

np.int64(1)

In [66]:
a[0:9:2]

array([1, 3])

In [67]:
d

array([[1, 2, 7],
       [3, 4, 8]])

In [68]:
d[0, 1]

np.int64(2)

In [69]:
d[0]

array([1, 2, 7])

In [70]:
d[:,1]

array([2, 4])

In [71]:
d[:,2]

array([7, 8])

In [72]:
d[:, 0:2]

array([[1, 2],
       [3, 4]])

In [73]:
d[0][0] = 9
d

array([[9, 2, 7],
       [3, 4, 8]])

In [74]:
d[0][0]

np.int64(9)

In [75]:
d[0, :] = 5
d

array([[5, 5, 5],
       [3, 4, 8]])

In [76]:
c

array([[1, 2, 3],
       [2, 2, 2],
       [3, 5, 6]])

In [77]:
a

array([1, 2, 3])

In [78]:
a.reshape(1, -1).shape

(1, 3)

In [79]:
np.random.seed(27)
np.random.randn(3, 2)

array([[ 1.28560542, -0.30355338],
       [ 0.61907566,  0.39599855],
       [ 0.22340565, -0.05433942]])

In [80]:
np.random.seed(27)
r = np.random.randn(1000)
r.shape

(1000,)

In [81]:
r.mean(), r.std()

(np.float64(-0.007501619644128666), np.float64(1.0275799264040038))

In [82]:
s = np.random.seed(27)
n = 16
s = np.random.randn(64, n)
s.shape

(64, 16)

In [83]:
q = np.random.randn(1, n)
q.shape

(1, 16)

In [84]:
# s_normed = s
(s**2).sum(axis=1)

array([ 8.15445015, 14.1711399 , 16.94004377, 15.95367015, 11.05309107,
       11.69910441, 15.03817352, 15.92013135, 16.07401998, 20.65985699,
        9.43227314, 23.14870381, 31.54829749, 11.56970398, 10.81227917,
        7.26194421, 20.71928341, 22.79508045, 18.8723012 , 14.48056337,
       17.18733065, 14.34914271, 21.515354  , 16.14604092, 12.07142747,
       26.59301501, 10.61231255, 10.91784   , 18.38747785, 17.51291294,
       22.23637615, 10.30180858, 23.18255732, 20.42048586, 25.55191314,
       17.32946596, 16.90009886, 14.04847744, 37.30578289, 15.78035437,
       15.20007227, 19.25371985, 17.12319084, 12.38758377, 22.08303825,
       17.84098518, 25.02522515, 11.89088291, 13.49050885, 20.19419315,
       13.40797678, 19.48362156,  8.75796638, 10.19807949, 16.06755808,
       15.40069727, 19.58047084, 16.85748604, 15.56081939, 14.75134283,
       22.21237426, 18.10302829,  9.25463169, 16.49262966])

In [85]:
# s_normed = s
(s**2).sum(axis=1).shape

(64,)

In [86]:
# s_normed = s
s / ((s**2).sum(axis=1)**0.5)[:, np.newaxis]

array([[ 0.45020504, -0.10630109,  0.21679357, ..., -0.35287986,
         0.42939604, -0.1857601 ],
       [-0.07318002, -0.07736662, -0.0630621 , ..., -0.23786194,
        -0.0453167 ,  0.45667513],
       [ 0.62487244, -0.04698447,  0.01980432, ...,  0.19720977,
        -0.36959972,  0.15085679],
       ...,
       [ 0.03302222,  0.40292209,  0.10009718, ...,  0.17043286,
        -0.00168982, -0.10516491],
       [-0.392899  ,  0.22810234, -0.12649078, ..., -0.16498684,
        -0.17427336, -0.10048912],
       [-0.17972889, -0.22152176,  0.14875569, ...,  0.03379282,
        -0.18829657, -0.09180758]], shape=(64, 16))

In [87]:
a[:, np.newaxis]

array([[1],
       [2],
       [3]])

In [88]:
s_normed = s / ((s**2).sum(axis=1)**0.5)[:, np.newaxis]
s_normed.shape

(64, 16)

In [125]:
(s_normed**2).sum(axis=1)**0.5

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
       1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
       1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
       1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [90]:
q_normed = q / ((q**2).sum(axis=1)**0.5)[:, np.newaxis]
q_normed.shape

(1, 16)

In [91]:
(q_normed**2).sum(axis=1)**0,5

(array([1.]), 5)

In [92]:
x, x.shape

(array([[1, 2, 3]]), (1, 3))

In [94]:
z = x.squeeze()
z, z.shape

(array([1, 2, 3]), (3,))

In [95]:
y, y.shape

(array([[7],
        [8],
        [9]]),
 (3, 1))

In [115]:
z = y.squeeze()
z, z.shape

(array([7, 8, 9]), (3,))

In [119]:
z, z.shape

(array([7, 8, 9]), (3,))

In [117]:
np.expand_dims(z, axis=-1).shape

(3, 1)

In [120]:
z, z.shape

(array([7, 8, 9]), (3,))